### PR TITLE
add ci-linter

### PR DESCRIPTION
**Pull request by ruslan-korneev**
Please, follow to PEP8!
Create this ci-linter for test your pull-requests and before merge you can refactore your code

### CODE REVIEW

**Comment by F0rzend** [comment]
Может сразу mypy добавить. А ещё я создал бы dev-requirements.txt с подобными зависимостями?

**Comment by shaggy-axel** [comment]
@F0rzend 
> I think it's worth adding mypy. You also need to add dependencies (mypy, flake8, isort, etc) to `backend/dev-requirements.txt`

I think, that adding this libs to dev-requirements is other side, and it's not required for github-workflows/actions.
In dev requirements should be other libs/frameworks, not for linter
But! This is `CI-Linter`, and for `CI-Tests` you can add dependencies to `backend/dev-requirements.txt` and use it in actions

**Comment by shaggy-axel** [comment]
@F0rzend 
> I think it's worth adding mypy. You also need to add dependencies (mypy, flake8, isort, etc) to `backend/dev-requirements.txt`

Ok, now I add `lint-requirements.txt` and replaced all linter runners to `backend/scripts/run-linter.sh` to make it easier to add new linter tools or change existing

**Comment by ilyachch** [comment]
Don't you think it should be done after some code will be written?
Why used `requirements.txt`? maybe there will be used poetry, pipenv, etc?

Why did you added matrix in workflow? matrix should be used in case, it project is library

I think this PR should be closed

**Comment by shaggy-axel** [comment]
@ilyachch Thanks for your opinion, but I think, that this feature should be in repo before some contributor push code and this ci-linter let more simple code review for maintainer.
What about `requrements.txt`, I call `lint-requirements.txt` just for ci-linter, not for development process.

**Pull request closed without merging**
